---
title: "Labour Mobility Second Test. Bigger and bigglier. NO SHAME!"
author: "Jackson"
date: "2017-06-28"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RCurl)
library(tidyverse)
library(scales)

LabMobABS <- read.csv(url("https://raw.githubusercontent.com/youngstreetinitiative/brusselssproutsideas/master/Data/LabourMobility.csv?token=AWGs-0Swr2R_efVrTtNE5FY1epy8Kuyqks5ZXJSBwA%3D%3D"))

LabMobIndustryABS <- read.csv(url("https://raw.githubusercontent.com/youngstreetinitiative/brusselssproutsideas/master/Data/Labour%20Mobility%20By%20Industry.csv?token=AWGs-0kHmTZS7oyZmygIunKuHwU2rjd0ks5ZXJQ-wA%3D%3D"))

ReasonCeasedEmpABS <- read.csv(url("https://raw.githubusercontent.com/youngstreetinitiative/brusselssproutsideas/master/Data/Reasons%20Ceasing%20Employment.csv?token=AWGs-8buS4tZltJD7XxtdbnPkNDP_FzDks5ZXJSowA%3D%3D"))

ABSLabourMobility <- merge(LabMobABS,merge(LabMobIndustryABS,ReasonCeasedEmpABS,all = T),all = T) %>% 
  mutate(Date=as.Date(Date,format="%d/%m/%Y")) %>% arrange(Date)
```


##  Labour Mobility in Australia from 1975-2016 Continued...
***
Graphs still needs to be adjusted for:

* Lack of data between 1987 and 1994
* Inclusion of change in locality but not employer individuals from 1994 to 2004

```{r eval=T,echo=T, out.width='960px'}
ChangeEmpIndustry <- LabMobIndustryABS %>% 
  mutate(Date=as.Date(Date,format="%d/%m/%Y"),
         Agriculture=Agriculture_ChangeEmp/Agriculture_Count,
         MiningUtilities=MiningUtilities_ChangeEmp/MiningUtilities_Count,
         Manufacturing=Manufacturing_ChangeEmp/Manufacturing_Count,
         Construction=Construction_ChangeEmp/Construction_Count,
         WholesaleRetail=WholesaleRetail_ChangeEmp/WholesaleRetail_Count,
         TransportStorageCommunications=TransportStorageCommunications_ChangeEmp/
           TransportStorageCommunications_Count,
         FinanceBusinessServ=FinanceBusinessServ_ChangeEmp/FinanceBusinessServ_Count,
         CommunityServ=CommunityServ_ChangeEmp/CommunityServ_Count,
         PublicAdmin=PublicAdmin_ChangeEmp/PublicAdmin_Count,
         EntertainmentHotelsPersonalServ=EntertainmentHotelsPersonalServ_ChangeEmp/
           EntertainmentHotelsPersonalServ_Count) %>% 
  select(Date,Agriculture,MiningUtilities,Manufacturing,Construction,WholesaleRetail,
         TransportStorageCommunications,FinanceBusinessServ,CommunityServ,
         PublicAdmin,EntertainmentHotelsPersonalServ) %>%
  gather(key=Industry,value=Proportion,-Date)
```

```{r eval=T,echo=T, out.width='960px'}
ggplot(ChangeEmpIndustry %>% filter(Industry %in% c("Agriculture","MiningUtilities",
                                                    "Manufacturing","TransportStorageCommunications",
                                                    "Construction")),
       aes(x=Date,y=Proportion,colour=Industry))+
  geom_line() + 
  scale_y_continuous(limits=c(0,0.26),breaks=c(seq(0,0.25,0.05)),labels=scales::percent)+
  scale_x_date(breaks = date_breaks("3 years"),labels=date_format("%Y"))+
  ylab("Proportion of Workers Employed at Survey")+xlab("Year")+
  theme(legend.position="top",legend.title = element_blank())
```


```{r eval=T,echo=T, out.width='960px'}
ggplot(ChangeEmpIndustry %>% filter(Industry %in% c("WholesaleRetail",
                                                    "FinanceBusinessServ","CommunityServ",
                                                    "PublicAdmin","EntertainmentHotelsPersonalServ")),
       aes(x=Date,y=Proportion,colour=Industry))+
  geom_line() + 
  scale_y_continuous(limits=c(0,0.26),breaks=c(seq(0,0.25,0.05)),labels=scales::percent)+
  scale_x_date(breaks = date_breaks("3 years"),labels=date_format("%Y"))+
  ylab("Proportion of Workers Employed at Survey")+xlab("Year")+
  theme(legend.position="top",legend.title = element_blank())
```